version: "3"
services:
  db:
    image: postgres:9.4.18-alpine
    environment:
      - POSTGRES_PASSWORD=super-secret
      - POSTGRES_DB=monitor_api
    privileged: true
    ports:
      - "15432:5432"
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4567:4567"
    links:
      - db
      - notify_simulator
    command: "bundle exec rerun --background 'ash bin/serve.sh'"
    privileged: true
    environment:
      DATABASE_URL: 'postgres://postgres:super-secret@db/monitor_api'
      PROJECT_FILE_PATH: 'projects.json'
      GOV_NOTIFY_API_URL: 'http://notify_simulator'
      EMAIL_WHITELIST: 'test@test.test'
      GOV_NOTIFY_API_KEY: 'cafe-cafecafe-cafe-cafe-cafe-cafecafecafe-cafecafe-cafe-cafe-cafe-cafecafecafe'

  notify_simulator:
    build: .
    volumes:
      - ./:/app
    ports:
      - "7654:4567"
    privileged: true
    command: "bundle exec rerun --background -- ruby ./simulators/notify.rb -o 0.0.0.0 -p 80"
